// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: src/prompt/prompt.proto

package prompt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Prompt_Connect_FullMethodName = "/prompt.Prompt/Connect"
)

// PromptClient is the client API for Prompt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Text, Close], error)
}

type promptClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptClient(cc grpc.ClientConnInterface) PromptClient {
	return &promptClient{cc}
}

func (c *promptClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Text, Close], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Prompt_ServiceDesc.Streams[0], Prompt_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Text, Close]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Prompt_ConnectClient = grpc.ClientStreamingClient[Text, Close]

// PromptServer is the server API for Prompt service.
// All implementations must embed UnimplementedPromptServer
// for forward compatibility.
type PromptServer interface {
	Connect(grpc.ClientStreamingServer[Text, Close]) error
	mustEmbedUnimplementedPromptServer()
}

// UnimplementedPromptServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptServer struct{}

func (UnimplementedPromptServer) Connect(grpc.ClientStreamingServer[Text, Close]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPromptServer) mustEmbedUnimplementedPromptServer() {}
func (UnimplementedPromptServer) testEmbeddedByValue()                {}

// UnsafePromptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptServer will
// result in compilation errors.
type UnsafePromptServer interface {
	mustEmbedUnimplementedPromptServer()
}

func RegisterPromptServer(s grpc.ServiceRegistrar, srv PromptServer) {
	// If the following call pancis, it indicates UnimplementedPromptServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Prompt_ServiceDesc, srv)
}

func _Prompt_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PromptServer).Connect(&grpc.GenericServerStream[Text, Close]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Prompt_ConnectServer = grpc.ClientStreamingServer[Text, Close]

// Prompt_ServiceDesc is the grpc.ServiceDesc for Prompt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prompt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prompt.Prompt",
	HandlerType: (*PromptServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Prompt_Connect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "src/prompt/prompt.proto",
}
